version: "3.8"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "1234:80"
        restart: always
        volumes:
            - ./src:/var/www/html

    db:
        image: mariadb:10.9.3
        restart: always
        environment:
            MARIADB_DATABASE: data
            MARIADB_ROOT_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    adminer:
        image: adminer
        ports:
            - '1235:8080'

volumes:
    db_data: